import { NextPage } from "next";
import Head from "next/head";

const HeadElement: NextPage = () => {
  return (
    <Head>
      <title>Encommerce Product page</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon-32x32.png" />
    </Head>
  );
};

export default HeadElement;
